# Generated by Django 5.2.7 on 2025-11-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openclose', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=10, verbose_name='Status')),
                ('dept', models.CharField(max_length=100, verbose_name='Department')),
                ('users', models.CharField(max_length=100, verbose_name='User')),
                ('totalrefund', models.IntegerField(default=0, verbose_name='Total Refund')),
                ('totalclaim', models.IntegerField(default=0, verbose_name='Total Claim')),
                ('totalchargeback', models.IntegerField(default=0, verbose_name='Total Chargeback')),
                ('totalpa61', models.IntegerField(default=0, verbose_name='Total PA61')),
                ('page', models.CharField(choices=[('LIRR', 'LIRR'), ('MNR', 'MNR')], max_length=10, verbose_name='Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Summary',
                'verbose_name_plural': 'Transaction Summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page', 'dept'], name='home_transa_page_c42961_idx'), models.Index(fields=['openclose'], name='home_transa_openclo_d106d0_idx')],
            },
        ),
    ]
